/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sortList {
	int listSize1;
	int listSize2;
	int sortedList1[100];
	int sortedList2[100];
	int list1[100];
	int list2[100];
};
typedef struct sortList sortList;

struct encryptedEcho {
	char message[1000];
};
typedef struct encryptedEcho encryptedEcho;

struct complex {
	float real1;
	float imag1;
	float real2;
	float imag2;
	float resultReal;
	float resultImag;
};
typedef struct complex complex;

#define RPC_Assignment 0x31111111
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getHostName 1
extern  char ** gethostname_1(void *, CLIENT *);
extern  char ** gethostname_1_svc(void *, struct svc_req *);
#define sort 2
extern  sortList * sort_1(sortList *, CLIENT *);
extern  sortList * sort_1_svc(sortList *, struct svc_req *);
#define printEncryptedEcho 3
extern  char ** printencryptedecho_1(encryptedEcho *, CLIENT *);
extern  char ** printencryptedecho_1_svc(encryptedEcho *, struct svc_req *);
#define listFiles 4
extern  char ** listfiles_1(void *, CLIENT *);
extern  char ** listfiles_1_svc(void *, struct svc_req *);
#define addComplex 5
extern  complex * addcomplex_1(complex *, CLIENT *);
extern  complex * addcomplex_1_svc(complex *, struct svc_req *);
extern int rpc_assignment_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getHostName 1
extern  char ** gethostname_1();
extern  char ** gethostname_1_svc();
#define sort 2
extern  sortList * sort_1();
extern  sortList * sort_1_svc();
#define printEncryptedEcho 3
extern  char ** printencryptedecho_1();
extern  char ** printencryptedecho_1_svc();
#define listFiles 4
extern  char ** listfiles_1();
extern  char ** listfiles_1_svc();
#define addComplex 5
extern  complex * addcomplex_1();
extern  complex * addcomplex_1_svc();
extern int rpc_assignment_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sortList (XDR *, sortList*);
extern  bool_t xdr_encryptedEcho (XDR *, encryptedEcho*);
extern  bool_t xdr_complex (XDR *, complex*);

#else /* K&R C */
extern bool_t xdr_sortList ();
extern bool_t xdr_encryptedEcho ();
extern bool_t xdr_complex ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
