/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_sortList (XDR *xdrs, sortList *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (2 +  100  + 100  + 100  + 100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->listSize1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->listSize2))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->sortedList1, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->sortedList2, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->list1, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->list2, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->listSize1);
			IXDR_PUT_LONG(buf, objp->listSize2);
			{
				register int *genp;

				for (i = 0, genp = objp->sortedList1;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->sortedList2;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->list1;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->list2;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (2 +  100  + 100  + 100  + 100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->listSize1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->listSize2))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->sortedList1, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->sortedList2, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->list1, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->list2, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->listSize1 = IXDR_GET_LONG(buf);
			objp->listSize2 = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->sortedList1;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->sortedList2;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->list1;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->list2;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->listSize1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->listSize2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->sortedList1, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->sortedList2, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->list1, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->list2, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_encryptedEcho (XDR *xdrs, encryptedEcho *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->message, 1000,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_complex (XDR *xdrs, complex *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->real1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->imag1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->real2))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->imag2))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->resultReal))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->resultImag))
		 return FALSE;
	return TRUE;
}
