/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <string.h>
#include <stdio.h>



// sorts and merges the array
void merge(int arr[], int l, int m, int r) 
{ 
    int i, j, k; 
    int n1 = m - l + 1; 
    int n2 =  r - m; 
  
    /* create temp arrays */
    int L[n1], R[n2]; 
  
    /* Copy data to temp arrays L[] and R[] */
    for (i = 0; i < n1; i++) 
        L[i] = arr[l + i]; 
    for (j = 0; j < n2; j++) 
        R[j] = arr[m + 1+ j]; 
  
    /* Merge the temp arrays back into arr[l..r]*/
    i = 0; // Initial index of first subarray 
    j = 0; // Initial index of second subarray 
    k = l; // Initial index of merged subarray 
    while (i < n1 && j < n2) 
    { 
        if (L[i] <= R[j]) 
        { 
            arr[k] = L[i]; 
            i++; 
        } 
        else
        { 
            arr[k] = R[j]; 
            j++; 
        } 
        k++; 
    } 
  
    /* Copy the remaining elements of L[], if there 
       are any */
    while (i < n1) 
    { 
        arr[k] = L[i]; 
        i++; 
        k++; 
    } 
  
    /* Copy the remaining elements of R[], if there 
       are any */
    while (j < n2) 
    { 
        arr[k] = R[j]; 
        j++; 
        k++; 
    } 
} 

// mergesort
void mergeSort(int arr[], int l, int r) 
{ 
    if (l < r) 
    { 
        // Same as (l+r)/2, but avoids overflow for 
        // large l and h 
        int m = l+(r-l)/2; 
  
        // Sort first and second halves 
        mergeSort(arr, l, m); 
        mergeSort(arr, m+1, r); 
  
        merge(arr, l, m, r); 
    } 
}

char **
gethostname_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	result = "host";
	return &result;
}


// gets lists from client and sorts them
sortList *
sort_1_svc(sortList *argp, struct svc_req *rqstp)
{
	static sortList  result;
	
	int i;
	int low = 0;
	int high = argp->listSize1 - 1;
	mergeSort(argp->list1, low, high);
	
	result.listSize1 = argp->listSize1;
	for(i =0; i<argp->listSize1; i++){
		result.sortedList1[i] = argp->list1[i];
	}
	
	low = 0;
	high = argp->listSize2 - 1;
	mergeSort(argp->list2, low, high);
	
	result.listSize2 = argp->listSize2;
	for(i =0; i<argp->listSize2; i++){
		result.sortedList2[i] = argp->list2[i];
	}

	return &result;
}

// encrypts the message, does -15 to each character in string
char **
printencryptedecho_1_svc(encryptedEcho *argp, struct svc_req *rqstp)
{
	static char * result;
	
	int i;
    for(i = 0; i < strlen(argp->message); i++)
    {
      argp->message[i] -= 15;
    }
	
	result = argp->message;

	return &result;
}


char **
listfiles_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	
	result = "directories";
		 
	return &result;
}


// adds two complex numbers
complex *
addcomplex_1_svc(complex *argp, struct svc_req *rqstp)
{
	static complex  result;

	result.resultReal = argp->real1 + argp->real2;
	result.resultImag = argp->imag1 + argp->imag1;

	return &result;
}
