/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <dirent.h> 

// reads complex numbers
readComplexNumbers(complex *complexNumber){
	float real1;
	float imag1;
	
	float real2;
	float imag2;
	
	float resultReal;
	float resultImag;
	
	printf("Enter real part for complex number1:");
	scanf("%f", &real1);
	complexNumber->real1 = real1;
	
	printf("Enter real part for imaginary number1:");
	scanf("%f", &imag1);
	complexNumber->imag1 = imag1;

	printf("Enter real part for complex number2:");
	scanf("%f", &real2);
	complexNumber->real2 = real2;

	printf("Enter real part for imaginary number2:");
	scanf("%f", &imag2);
	complexNumber->imag2 = imag2;

}

// reads lists that need to be sorted
readLists(sortList *sList){
	int i;
	int size1;
	int size2;
	int readValue;
	
	// to read list size from user
	printf("enter size of the list1: ");
	scanf("%d",&size1);
	sList->listSize1 = size1;
	// reading in list values
	printf("enter list1 elements:");
	for (i=0;i<size1;i++){
		scanf("%d", &readValue);
		sList->list1[i] = readValue;
	}
	
	// to read list size from user
	printf("enter size of the list2:");
	scanf("%d",&size2);
	sList->listSize2 = size2;
	// reading in list values
	printf("enter list2 elements:");
	for (i=0;i<size2;i++){
		scanf("%d", &readValue);
		sList->list2[i] = readValue;
	}
}

void
rpc_assignment_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *gethostname_1_arg;
	sortList  *result_2;
	sortList  sort_1_arg;
	char * *result_3;
	encryptedEcho  printencryptedecho_1_arg;
	char * *result_4;
	char *listfiles_1_arg;
	complex  *result_5;
	complex  addcomplex_1_arg;
	int choice;
	char message[1000];
	struct dirent *de;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_Assignment, RPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	do{
		/* Menu for user on client */
		printf("*******************Menu*********************\n");
		printf("1) Get Hostname \n");
		printf("2) Sort List\n");
		printf("3) Encrypted Echo\n");
		printf("4) List Files \n");
		printf("5) add complex numbers\n");
		printf("6) Exit\n");
		printf("Enter your choice:\n");
		scanf("%d",&choice);
		switch(choice){
			// prints out host name
			case 1:
				result_1 = gethostname_1((void*)&gethostname_1_arg, clnt);
				if (result_1 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}else{
					printf("Host name is: %s \n", host);
				}
				break;
				
			// reads and calls merger sort on server		
			case 2:	
				readLists(&sort_1_arg);
				result_2 = sort_1(&sort_1_arg, clnt);
				if (result_2 == (sortList *) NULL) {
					clnt_perror (clnt, "call failed");
				}else{
					int i=0;
					
					int size = result_2->listSize1;
					printf("size: %d \n", size);
					printf("printing sorted list1: \n");
					for (i=0;i<size;i++){
						printf("%d ", result_2->sortedList1[i]);
					}
					printf("\n");
					
					size = result_2->listSize2;
					printf("size: %d \n", size);
					printf("printing sorted list1: \n");
					for (i=0;i<size;i++){
						printf("%d ", result_2->sortedList2[i]);
					}
					printf("\n");

				}
				break;
			
			// reads message, sends it to servers where it gets encrypted and prints it out on server
			case 3:
				printf("Enter something to echo on server:\n");
				scanf("%s", &message);
				strcpy(printencryptedecho_1_arg.message,message);

				result_3 = printencryptedecho_1(&printencryptedecho_1_arg, clnt);
				if (result_3 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}else{
					printf(" Encrypted message is: %s \n", *result_3);
				}
				break;
			
			// lists out all directories and files in current directory 
			case 4:
				result_4 = listfiles_1((void*)&listfiles_1_arg, clnt);
				if (result_4 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}else{
					DIR *dr = opendir("."); 
					if (dr == NULL){ 
						printf("Could not open current directory" ); 
					} 
					// for readdir() 
					while ((de = readdir(dr)) != NULL) 
							printf("%s\n", de->d_name); 
					closedir(dr); 
					
					printf("\n");
				}
				break;
			
			// reads 2 complex numbers and adds thems
			case 5:
				readComplexNumbers(&addcomplex_1_arg);
				result_5 = addcomplex_1(&addcomplex_1_arg, clnt);
				if (result_5 == (complex *) NULL) {
					clnt_perror (clnt, "call failed");
				}else{
					printf("Sum = %.1f + %.1fi \n", result_5->resultReal, result_5->resultImag);
				}
				break;
			case 6:
				exit(0);
				break;
			default:
				printf("invalid choice");
				break;
		}
	}while(1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_assignment_1 (host);
exit (0);
}
